version: '3.9'
services:

  app:
    container_name: "mvc_service"
    build:
      context: .
      dockerfile: Dockerfile
    image: my_app
    ports:
      - "8081:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/mvc_project_db
      - spring.datasource.password=root
    depends_on:
      - db
    restart: always
  db:
    container_name: my_app_db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: mvc_project_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"